"""Initial migration

Revision ID: f5f984b738e0
Revises: 
Create Date: 2024-03-21 13:01:51.800573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f984b738e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('art_id', sa.String(length=22), nullable=True),
    sa.Column('art_name', sa.String(length=150), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=70), nullable=True),
    sa.Column('genre2', sa.String(length=70), nullable=True),
    sa.Column('genre3', sa.String(length=70), nullable=True),
    sa.Column('img_url', sa.String(length=150), nullable=True),
    sa.Column('img_url_mid', sa.String(length=150), nullable=True),
    sa.Column('img_url_sml', sa.String(length=150), nullable=True),
    sa.Column('master_genre', sa.String(length=150), nullable=True),
    sa.Column('app_record_date', sa.String(length=150), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recently_played',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('art_name', sa.String(length=150), nullable=True),
    sa.Column('song_name', sa.String(length=150), nullable=True),
    sa.Column('song_link', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=150), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('art_name', sa.String(length=150), nullable=True),
    sa.Column('album_id', sa.String(), nullable=True),
    sa.Column('album_name', sa.String(length=150), nullable=True),
    sa.Column('song_id', sa.String(length=70), nullable=True),
    sa.Column('song_name', sa.String(length=270), nullable=True),
    sa.Column('img_url', sa.String(length=150), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('app_record_date', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('artist_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('artist_catalog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_catalog_id'], ['artist_catalog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('art_id', sa.String(length=23), nullable=False),
    sa.Column('art_name', sa.String(length=150), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['art_id'], ['artist_catalog.id'], name='fk_daily_artists_art_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('art_id', sa.String(length=23), nullable=False),
    sa.Column('art_name', sa.String(length=150), nullable=True),
    sa.Column('album_name', sa.String(length=150), nullable=True),
    sa.Column('song_id', sa.String(length=23), nullable=True),
    sa.Column('song_name', sa.String(length=150), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['art_id'], ['artist_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_name', sa.String(), nullable=True),
    sa.Column('playlist_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('track_name', sa.String(length=150), nullable=True),
    sa.Column('art_id', sa.String(length=23), nullable=False),
    sa.Column('art_name', sa.String(length=150), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['art_id'], ['artist_catalog.id'], name='fk_daily_artists_art_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlists')
    op.drop_table('daily_tracks')
    op.drop_table('daily_artists')
    op.drop_table('blog_comments')
    op.drop_table('artist_comments')
    op.drop_table('user_accounts')
    op.drop_table('track_catalog')
    op.drop_table('recently_played')
    op.drop_table('blog_posts')
    op.drop_table('artist_catalog')
    # ### end Alembic commands ###
