"""Added medium, theme1, and theme2 columns to blog_posts table

Revision ID: fa4f05e59068
Revises: f5f984b738e0
Create Date: 2024-04-11 12:03:05.001019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4f05e59068'
down_revision = 'f5f984b738e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medium', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('theme1', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('theme2', sa.String(length=50), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('post_date',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('post_date',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('theme2')
        batch_op.drop_column('theme1')
        batch_op.drop_column('medium')

    # ### end Alembic commands ###
